<?xml version="1.0" encoding="UTF-8"?>

<!-- Определение DTD  -->
<!DOCTYPE catalog
[
  <!ELEMENT catalog (book) >
  <!ELEMENT book (title, author, price) >
  <!ELEMENT title (#PCDATA) >
  <!ELEMENT author (#PCDATA) >
  <!ELEMENT price (#PCDATA) >
]>

<!-- Объявление корневого элемента, описанного по DTD  -->

<catalog>
	<book>
		<title>Название</title>
		<author>Автор</author>
		<price>200</price>
  </book>
</catalog>


