<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE catalog [
  <!ELEMENT catalog (book+) >
  <!ELEMENT book (title, author+, price, publisher?) >
  <!ELEMENT title (#PCDATA) >  <!-- #Тип данных элемента -->
  <!ELEMENT author (#PCDATA) >
  <!ELEMENT price (#PCDATA) >
  <!ELEMENT publisher (#PCDATA) >
]>

<!--
Квантификаторы: - задают количество элементов, что может содержаться в другом элементе (book)
+ -> от одного и больше
* -> от нуля и больше
? -> ноль или один
-->

<catalog>
	<book>
		<title>Название</title>
		<author>Автор</author>
		<price>123.00</price>
		<publisher>BHV</publisher>
	</book>
	<book>
		<title>Название</title>
		<author>Автор</author>
		<price>123.00</price>
	</book>
	<book>
		<title>Название</title>
		<author>Автор</author>
    <author>Автор</author>
		<price>123.00</price>
		<publisher>Williams</publisher>
	</book>
</catalog>

