<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog
[
  <!ELEMENT catalog (book+) > <!--Сложные элементы содержат в себе элементы-->
  <!ELEMENT book (title, author+, price, publisher?) >
  
  <!--Простые элементы с типом PCDATA-->
  <!ELEMENT title (#PCDATA) >
  <!ELEMENT author (#PCDATA) >
  <!ELEMENT price (#PCDATA) >
  <!ELEMENT publisher (#PCDATA) >
  
  <!--Объявление атрибутов:
  <!ATTLIST имя-элемента имя-атрибута тип-значения обязательность> 
  -->
  
  <!ATTLIST book isbn CDATA #IMPLIED>
  <!ATTLIST price currency CDATA #REQUIRED>
]>

<catalog>
	<book isbn='456-123-45632'>
		<title>Название</title>
		<author>Автор</author>
		<price currency='RUR'>123.00</price>
		<publisher>BHV</publisher>
	</book>
	<book>
		<title>Название</title>
		<author>Автор</author>
		<price currency='RUR'>123.00</price>
	</book>
	<book isbn='736-738-9948'>
		<title>Название</title>
		<author>Автор</author>
    <author>Автор</author>
		<price currency='RUR'>123.00</price>
		<publisher>Williams</publisher>
	</book>
</catalog>

